# Generated by Django 5.0.6 on 2024-08-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_alter_login_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='photo',
            field=models.ImageField(default='doctors/default admin.png', upload_to='doctors/'),
        ),
    ]
