# Generated by Django 5.0.6 on 2024-08-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoradd',
            name='mobile',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctoradd',
            name='qualification',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
