# Generated by Django 5.0.6 on 2024-08-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0010_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
