# Generated by Django 5.0.6 on 2024-08-30 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_statusreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.schedule'),
        ),
    ]
